name: Run fetch_menu script

on:
  schedule:
    - cron: '0 20 * * 0'  # This runs the action every Sunday at 8pm

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib

    - name: Execute fetch_menu script
      run: main.py

    - name: Commit and push if changes
      run: |
        git add -A
        git commit -m "Add new menu image"
        git push
